package com.example.fitnessapp.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF006782)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFBBE9FF)
val OnPrimaryContainerLight = Color(0xFF001F29)
val SecondaryLight = Color(0xFF4C616B)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCFE6F1)
val OnSecondaryContainerLight = Color(0xFF071E26)
val TertiaryLight = Color(0xFF5A5C7E)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFE0E0FF)
val OnTertiaryContainerLight = Color(0xFF171937)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFBFCFE)
val OnBackgroundLight = Color(0xFF191C1E)
val SurfaceLight = Color(0xFFFBFCFE)
val OnSurfaceLight = Color(0xFF191C1E)

val PrimaryDark = Color(0xFF60D4FE)
val OnPrimaryDark = Color(0xFF003544)
val PrimaryContainerDark = Color(0xFF004D62)
val OnPrimaryContainerDark = Color(0xFFBBE9FF)
val SecondaryDark = Color(0xFFB3CAD5)
val OnSecondaryDark = Color(0xFF1E333C)
val SecondaryContainerDark = Color(0xFF354A53)
val OnSecondaryContainerDark = Color(0xFFCFE6F1)
val TertiaryDark = Color(0xFFC3C3EA)
val OnTertiaryDark = Color(0xFF2C2E4D)
val TertiaryContainerDark = Color(0xFF424465)
val OnTertiaryContainerDark = Color(0xFFE0E0FF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF191C1E)
val OnBackgroundDark = Color(0xFFE1E2E4)
val SurfaceDark = Color(0xFF191C1E)
val OnSurfaceDark = Color(0xFFE1E2E4)
